# Generated by Django 3.1.4 on 2021-01-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_desc', models.TextField()),
                ('github_link', models.CharField(max_length=250)),
                ('demo_file', models.FileField(null=True, upload_to='demos')),
            ],
        ),
    ]
