# Generated by Django 3.1.4 on 2021-01-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0003_project_live_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_file',
            field=models.FileField(blank=True, null=True, upload_to='demos'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
