# Generated by Django 3.1.4 on 2021-01-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0006_education_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
